[preferred]
default=gtk;
org.freedesktop.impl.portal.ScreenCast=gtk;wlr;
org.freedesktop.impl.portal.Screenshot=gtk;wlr;
org.freedesktop.impl.portal.Settings=gtk
org.freedesktop.impl.portal.FileChooser=gtk
